version: '3.8'
services:
  kbook-app:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - ./k-book-app/package.json:/kbook-app/package.json
      - ./k-book-app/package-lock.json:/kbook-app/package-lock.json
      - ./k-book-app/src/:/kbook-app/src